FROM 3a037473928d
RUN  mkdir /www/wwroot
WORKDIR /www
VOLUME /www/wwwroot/dingqueue:/www
VOLUME /www/volumn/nginx/:/usr/local/nginx/conf/
VOLUME /www/volumn/php/:/usr/local/php/etc
VOL
CMD ["service","nginx start"]
EXPOSE 86:80