version: '2.0'

services:
  rabbit01:
    image: rabbitmq:3-management
    container_name: rabbit01
    hostname: rabbit01
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
      - 25672:25672
    expose:
      - 15672
      - 5672
      - 25672
    networks:
      net1:
        ipv4_address: 172.17.0.10
    privileged: true
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_ERLANG_COOKIE: rabbitmq_cookie

  rabbit02:
    image: rabbitmq:3-management
    container_name: rabbit02
    hostname: rabbit02
    restart: always
    ports:
      - 15673:15672
      - 5673:5672
      - 25673:25672
    expose:
      - 15672
      - 5672
      - 25672
    networks:
      net1:
        ipv4_address: 172.17.0.11
    privileged: true
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_ERLANG_COOKIE: rabbitmq_cookie

  rabbit03:
    image: rabbitmq:3-management
    container_name: rabbit03
    restart: always
    hostname: rabbit03
    ports:
      - 15674:15672
      - 5674:5672
      - 25674:25672
    expose:
      - 15672
      - 5672
      - 25672
    networks:
      net1:
        ipv4_address: 172.17.0.12
    privileged: true
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_ERLANG_COOKIE: rabbitmq_cookie

networks:
  net1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.0.0/16
          gateway: 172.17.0.1
